server:
  port: 8083

spring:
  main:
    web-application-type: reactive

  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Vary

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: cadastro
          uri: lb://CADASTRO
          predicates:
            - Path=/cadastro/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5 #limites de requests
                redis-rate-limiter.burstCapacity: 10

        - id: anamnese
          uri: lb://ANAMNESE
          predicates:
            - Path=/anamnese/**
        - id: openfoodfacts
          uri: lb://OPENFOODFACTS
          predicates:
            - Path=/openfoodfacts/**
        - id: historico
          uri: lb://HISTORICO
          predicates:
            - Path=/history/**
        - id: email
          uri: lb://EMAIL
          predicates:
            - Path=/email/**
        - id: favorite
          uri: lb://FAVORITE
          predicates:
            - Path=/favorite/**
  data:
    redis:
      host: localhost #server do redis, o redis cuida da limitacao de requisicoes
      port: 6379

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service

      - url: /cadastro/v3/api-docs
        name: User API Service

      - url: /anamnese/v3/api-docs
        name: Anamnese API Service

      - url: /openfoodfacts/v3/api-docs
        name: Open Food Facts API Service

      - url: /historico/v3/api-docs
        name: Historico API Service

      - url: /email/v3/api-docs
        name: E-mail API Service

      - url: /favorite/v3/api-docs
        name: Favotire API Service

eureka: #nessa parte, mostramos como o servico se registra no eureka, se nao for feito, nao sera possivel encontrar
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/  #link do server eureka
