services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=ms-cadastro'
      - 'POSTGRES_PASSWORD=senha123'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    networks:
      - nt-ms-cadastro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'
    networks:
      - nt-ms-cadastro

  ms-cadastro:
    build: .
    ports:
      - '8081:8081'
    environment:
      - 'spring.datasource.url=jdbc:postgresql://postgres:5432/ms-cadastro'
      - 'spring.datasource.username=postgres'
      - 'spring.datasource.password=senha123'
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started

    networks:
      - nt-ms-cadastro

networks:
  nt-ms-cadastro:
    driver: bridge